services:
  web:
    build: .
    command: make run
    volumes:
        - .:/app
        - /var/radical/logs:/app/logs
        - /var/radical/media:/app/media
        - /var/radical/database:/app/db
    ports:
        - "8082:8000"
    environment:
        - PYTHONDONTWRITEBYTECODE=1
        - PYTHONUNBUFFERED=1